repository: pycaonau/2018.pycon-au.org

port: 4000
base_author: "the Organisers"
permalink: /news/:title/

encoding: "bom|utf-8"

# Navigation
navigationLinks:
 - {permalink: '/about/', text: "About"}
 - {permalink: '/news/', text: "News"}
 - {permalink: '/attend/', text: "Attend"}
 - {permalink: '/schedule/', text: "Schedule"}
 - {permalink: '/sponsor/', text: "Sponsor"}
 - {permalink: '/conduct/', text: "Conduct"}

conferenceDays:
 - Friday
 - Saturday
 - Sunday
 - Monday
 - Tuesday

attendLinks:
 - {permalink: '/attend/', text: "Attend"}
 - {permalink: '/attend/accommodation', text: "Accommodation"}
 - {permalink: '/attend/tickets', text: "Tickets"}
 - {permalink: '/attend/ticket-tiers', text: "Ticket Tiers"}
 - {permalink: '/attend/shirts', text: "Shirts"}
 - {permalink: '/attend/badges/', text: "Badges"}
 - {permalink: '/menu/', text: "Menu"}

menuLinks:
 - {permalink: '/menu/', text: "Menu"}
 - {permalink: '/menu/friday', text: "Friday"}
 - {permalink: '/menu/saturday', text: "Saturday"}
 - {permalink: '/menu/sunday', text: "Sunday"}
 - {permalink: '/menu/monday', text: "Monday"}
 - {permalink: '/menu/tuesday', text: "Tuesday"}

include: 
 - _pages

exclude:
 - README.md
 - CNAME
 - Gemfile
 - Gemfile.lock
 - new_post
 - vendor

future: true

timezone: "AEST"

collections:
    talks:  
        output: true
        permalink: /:collection/:title/

plugins:
  - jemoji
